language: python
dist: xenial
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
stages:
  - test
  - lint
  - wheels
env:
  - PATH=$HOME/.cargo/bin:$PATH
matrix:
  include:
    - python: '3.8'
      name: 'rust linters'
      install: true
      script:
        - cargo clippy || true
        - cargo fmt -- --check  || true
      stage: lint
    - python: '3.8'
      name: 'manylinux2010'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=the_drow
        - secure: "Bgd5Gwf0VOi6iqQAfaZJ/kIp9idyIMOgi1CGMLwfuOqHXgIxtf4ukB5Z1ZMAlPdRGNTquI/iJeUHmb9bCjvkLPInR9A2bgU5VfhChVdV3Sav8ATvvUHTctP+m0izRv/1IfVyIngV9qnwFlVYxq8M+SK3JmrL0tHuPXpnToeCXHoPhE1VbcRh9PrQyKaS7pdizSH5xQMWcSkrKVKVtfrP1ujhPj30Braeo3oC/fcoO5G8qXHhKF/KxddicNt54nghc2Jq0zLxULhDpWO1KbfaMiCxt7PgoVAuRGGF2Pk5cNkZCDoyiE+mRNcs+OxsZQJnxwAtti3fQ6uAsoWRDoBahJiMcAkxvQUrZaa2bUY9BLTYBsnBH0V01844guGmbfOYpvcuUM8dYW32p/dPlImH858RLsWKLXyr76FayZTN1/S5iSOja1pb4JwMvK+JbXC77yzJvfkJWmzxxKswhrA21H67TwtkV+T4fGHfJtsyv1L93dRHpaRgRTtsbqin43TJKFKFRuyXow0y1uB8dvUTqYfHYkqKhRYnhoGoxMOC6owmmqRGKoUm8s2epkr4FY/JZqAe3SMow1dUMqmg6gNPwCjq+D7ErS82xCiXduhgRCYIZg7Rc5DNlR3iJAbZzKYFOfo9zyN9NAvN2xNq785DAgEIb2VRhjpgAq1YHUOrcII="
      script:
        - sudo docker build -f manylinux2010.dockerfile -t fastuuid_manylinux2010:latest .
        - sudo docker run -e NO_SDIST="1" -e MANYLINUX_VERSION="2010" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src fastuuid_manylinux2010:latest
      stage: wheels
    - python: '3.8'
      name: 'manylinux2014'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=the_drow
        - secure: "Bgd5Gwf0VOi6iqQAfaZJ/kIp9idyIMOgi1CGMLwfuOqHXgIxtf4ukB5Z1ZMAlPdRGNTquI/iJeUHmb9bCjvkLPInR9A2bgU5VfhChVdV3Sav8ATvvUHTctP+m0izRv/1IfVyIngV9qnwFlVYxq8M+SK3JmrL0tHuPXpnToeCXHoPhE1VbcRh9PrQyKaS7pdizSH5xQMWcSkrKVKVtfrP1ujhPj30Braeo3oC/fcoO5G8qXHhKF/KxddicNt54nghc2Jq0zLxULhDpWO1KbfaMiCxt7PgoVAuRGGF2Pk5cNkZCDoyiE+mRNcs+OxsZQJnxwAtti3fQ6uAsoWRDoBahJiMcAkxvQUrZaa2bUY9BLTYBsnBH0V01844guGmbfOYpvcuUM8dYW32p/dPlImH858RLsWKLXyr76FayZTN1/S5iSOja1pb4JwMvK+JbXC77yzJvfkJWmzxxKswhrA21H67TwtkV+T4fGHfJtsyv1L93dRHpaRgRTtsbqin43TJKFKFRuyXow0y1uB8dvUTqYfHYkqKhRYnhoGoxMOC6owmmqRGKoUm8s2epkr4FY/JZqAe3SMow1dUMqmg6gNPwCjq+D7ErS82xCiXduhgRCYIZg7Rc5DNlR3iJAbZzKYFOfo9zyN9NAvN2xNq785DAgEIb2VRhjpgAq1YHUOrcII="
      script:
        - sudo docker build -f manylinux2014.dockerfile -t fastuuid_manylinux2014:latest .
        - sudo docker run -e MANYLINUX_VERSION="2014" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src fastuuid_manylinux2014:latest
      stage: wheels
    - python: '3.8'
      name: 'manylinux1'
      before_install: true
      install: true
      env:
        - PYPI_USERNAME=the_drow
        - secure: "Bgd5Gwf0VOi6iqQAfaZJ/kIp9idyIMOgi1CGMLwfuOqHXgIxtf4ukB5Z1ZMAlPdRGNTquI/iJeUHmb9bCjvkLPInR9A2bgU5VfhChVdV3Sav8ATvvUHTctP+m0izRv/1IfVyIngV9qnwFlVYxq8M+SK3JmrL0tHuPXpnToeCXHoPhE1VbcRh9PrQyKaS7pdizSH5xQMWcSkrKVKVtfrP1ujhPj30Braeo3oC/fcoO5G8qXHhKF/KxddicNt54nghc2Jq0zLxULhDpWO1KbfaMiCxt7PgoVAuRGGF2Pk5cNkZCDoyiE+mRNcs+OxsZQJnxwAtti3fQ6uAsoWRDoBahJiMcAkxvQUrZaa2bUY9BLTYBsnBH0V01844guGmbfOYpvcuUM8dYW32p/dPlImH858RLsWKLXyr76FayZTN1/S5iSOja1pb4JwMvK+JbXC77yzJvfkJWmzxxKswhrA21H67TwtkV+T4fGHfJtsyv1L93dRHpaRgRTtsbqin43TJKFKFRuyXow0y1uB8dvUTqYfHYkqKhRYnhoGoxMOC6owmmqRGKoUm8s2epkr4FY/JZqAe3SMow1dUMqmg6gNPwCjq+D7ErS82xCiXduhgRCYIZg7Rc5DNlR3iJAbZzKYFOfo9zyN9NAvN2xNq785DAgEIb2VRhjpgAq1YHUOrcII="
      script:
        - sudo docker build -f manylinux1.dockerfile -t fastuuid_manylinux1:latest .
        - sudo docker run -e NO_SDIST="1" -e MANYLINUX_VERSION="1" -e TRAVIS_TAG="$TRAVIS_TAG" -e PYPI_USERNAME="$PYPI_USERNAME" -e MATURIN_PASSWORD="$PYO3_PACK_PASSWORD" -v $PWD:/tmp/src fastuuid_manylinux1:latest
      stage: wheels
cache:
  pip: true
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    - $TRAVIS_BUILD_DIR/.hypothesis
before_cache:
  - sudo rm -R $TRAVIS_BUILD_DIR/target/wheels

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --component clippy rustfmt

install: pip install -U tox maturin tox-pyo3 tox-travis

script: tox
